### ISSUE TITLE
Overview Tracking Issue

### ISSUE THREAD

**Issue by lsaether** [w3f/Web3-wiki#20]
# Overview Tracking Issue

## Information

 - [ ] Comparison. Polkadot vs. {Cosmos,Tezos,Ethereum}
 - [ ] Cryptography Used
 - [ ] FAQ
 - [ ] Innovation
 - [ ] News
 - [ ] NPoS / Finality
 - [ ] Polkadot Roadmap
 - [ ] Shared Security
 - [ ] Terms and Definitions

### How Can I Build With Polkadot

 - [ ] Do I build a parachain or smart contract? List benefits of each type
 - [ ] Parachain: Start with Substrate runtime modules
 - [ ] Parachain: How do I deploy? Cumulus, collators, validator choice
 - [ ] Smart Contract: Edgeware?
 - [ ] Smart Contract: Substrate contracts module

### Parachain Tutorials

 - [ ] Deploying Your First Parachain
 - [ ] Running a Collator Node for Your Parachain
 - [ ] Making Your Substrate Chain Compatible With Polkadot **!From Parity**
 - [ ] Interchain Communication **!From Parity**

### Tools

 - [X] List tools for programming languages Rust, C++, Go, JS
 - [ ] Examples of using the tools
 - [ ] Examples of JS libs??
